config/routes.rb
Rails.application.routes.draw do
  get 'coaching/answer'

  get 'coaching/ask'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coaching_controller.rb
class CoachingController < ApplicationController
  def answer
    @question = params[:query]
    @answer = coach_answer_enhanced(@question)
  end

  def ask
  end

  private

  def coach_answer(your_message)
  # TODO: return coach answer to your_message
    if your_message.include? "?"
      return "Silly question, get dressed and go to work!"
    elsif your_message.include? "I am going to work right now!"
      return ""
    else
      return "I don't care, get dressed and go to work!"
    end
  end

  def coach_answer_enhanced(your_message)
    if your_message != your_message.upcase
      coach_answer(your_message)
    elsif your_message == "I am going to work right now!".upcase
      return ""
    else
      return "I can feel your motivation! " + coach_answer(your_message)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/views/coaching/answer.html.erb
<h1>Coaching#answer</h1>
<p><%= @question %></p>
<p> — You </p>
<p><%= @answer %></p>
<p> — Your coach </p>

<%= link_to "Ask a new question", coaching_ask_path %>

app/views/coaching/ask.html.erb
<h1>Coaching#ask</h1>

<form action="/coaching/answer">
  <label for="question">Speak to your coach</label>
  <input type="text" id="question" name="query" placeholder="what time is it?">
  <input type="submit" value="Go on!">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>